enc_id = '00Za02W1BNwK3yoVC3c1g9lUNzI4YRBfNmfg=='
password = '00Vwj8iDcTnwm1Fd6wEvmMrgMufcYZDvY='
salt = '6qdqmz'
key_pair = [
    [
    235,
    41,
    83,
    175,
    52,
    107,
    164,
    89,
    34,
    69,
    88,
    222,
    156,
    138,
    189,
    25,
    65,
    189,
    168,
    55,
    133,
    142,
    237,
    121,
    247,
    170,
    55,
    37,
    231,
    93,
    224,
    224,
    86,
    174,
    180,
    80,
    85,
    105,
    35,
    254,
    63,
    60,
    158,
    150,
    17,
    167,
    103,
    180,
    21,
    179,
    241,
    155,
    241,
    103,
    76,
    190,
    89,
    225,
    81,
    154,
    33,
    208,
    12,
    164,
],
    [
    86,
    174,
    180,
    80,
    85,
    105,
    35,
    254,
    63,
    60,
    158,
    150,
    17,
    167,
    103,
    180,
    21,
    179,
    241,
    155,
    241,
    103,
    76,
    190,
    89,
    225,
    81,
    154,
    33,
    208,
    12,
    164,
],
]
key_confirmed = true

[keys_confirmed]
rs-ny = true
